### ISSUE TITLE
it is showing 0 frames found even though there are 100 frames with jpg extension

### ISSUE THREAD

**Issue by shreyas-f3r** [thecodingbob/framebot#3]

**Comment by firesidegargoyle** [comment]
Ever figure this out? I'm having the same issue with a folder of 14,000 frames

**Comment by nicholasfreed** [comment]
Hey, sorry for the late answer. 
This issue it's usually a matter of quoted strings in the config.ini file. Check if it's frames_ext is quoted, like "jpg", and if it is, change it to just jpg, without the double quotes. Let me know if this was the problem.

**Comment by nicholasfreed** [comment]
Since the quoted extension was causing the issue for everyone I've spoken with about, I'm closing this issue (I've also fixed the file in the repo).
