### ISSUE TITLE
I cant upload the frames - Frame files naming issue

### ISSUE THREAD

**Issue by Deadterm1nator** [thecodingbob/framebot#6]
It gives me an error

![image](https://user-images.githubusercontent.com/88507580/148633873-2d902dd7-65d0-4320-ad26-344fb4a678b8.png)

**Comment by nicholasfreed** [comment]
Hi!

For now, the bot expects the frames to be named as numbers without any trailing string. If you use ffmpeg for the extraction, you should use this pattern for the file naming: `%05d.jpg`. Full example:
`ffmpeg -i .\tdw.mkv -r 1.5 -vf "subtitles='tdw.srt':force_style='Fontsize=22,Outline=1.8'" -q:v 2 .\frames\%05d.jpg`.

In an upcoming relase, you will have the chance to insert your own file naming pattern in the config.ini file.

**Comment by thecodingbob** [comment]
As of [this commit](https://github.com/thecodingbob/framebot/commit/5628aec7fbbcd0a6f3596a0287f8e7563f6856a3), you can now use custom file naming. Just set the correct pattern in the config.ini file.
