### ISSUE TITLE
Support to spanish

### ISSUE THREAD

**Issue by Deadterm1nator** [thecodingbob/framebot#7]
Hi!

I have a page of frames in spanish and i put the tittle of each episode in spanish, but sometimes it requires to put some accents in some word, so when i upload the frames with the text, it shows something like this. 
![image](https://user-images.githubusercontent.com/88507580/148670244-a36f6977-fa99-4f2d-a001-92956985c17a.png)

Can you please make an enhancement for this?

Thanks.

**Comment by Deadterm1nator** [comment]
It´s supposed to be an: í

**Comment by thecodingbob** [comment]
Should work as expected now. I'll wait for some feedback and then I'll close the issue.

**Comment by Deadterm1nator** [comment]
It worked.

Thanks!
